- name: add key for artifactory official repo
  apt_key: keyserver=pgpkeys.mit.edu id={{artifactory_pgp_id}}

- name: download debian package
  get_url: url={{artifactory_url}} dest=/tmp/artifactory.deb

- name: install artifactory package
  apt: deb=/tmp/artifactory.deb

- name: start artifactory
  service: name=artifactory state=started